// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "new_serverip": string;
      "sourceLang": string;
      "targetLang": string;
      "sourceLangSelect": string;
      "targetLangSelect": string;
      "engine": string;
      "engineSelect": string;
      "service": string;
      "serviceSelect": string;
      "next_service": string;
      "next_serviceSelect": string;
      "skipLastPages": number;
      "threadNum": number;
      "qps": number;
      "poolSize": number;
      "rename": boolean;
      "skipSubsetFonts": boolean;
      "babeldoc": boolean;
      "fontFile": string;
      "fontFamily": string;
      "dualMode": string;
      "transFirst": boolean;
      "ocr": boolean;
      "autoOcr": boolean;
      "noWatermark": boolean;
      "saveGlossary": boolean;
      "disableGlossary": boolean;
      "noDual": boolean;
      "noMono": boolean;
      "skipClean": boolean;
      "disableRichTextTranslate": boolean;
      "enhanceCompatibility": boolean;
      "translateTableText": boolean;
      "onlyIncludeTranslatedPage": boolean;
      "mono": boolean;
      "dual": boolean;
      "mono-cut": boolean;
      "dual-cut": boolean;
      "crop-compare": boolean;
      "compare": boolean;
      "mono-open": boolean;
      "dual-open": boolean;
      "mono-cut-open": boolean;
      "dual-cut-open": boolean;
      "crop-compare-open": boolean;
      "compare-open": boolean;
      "dialog-service": string;
      "dialog-serviceSelect": string;
    };
  }
}
